/*
 * Java
 *
 * Copyright 2014 IS2T. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be found at http://www.is2t.com/open-source-bsd-license/.
 */
package com.is2t.demo.utilities;

import com.is2t.demo.utilities.errors.ErrorHandler;

import ej.bon.Timer;
import ej.bon.TimerTask;

/**
 * Wraps a runnable in a timer task.
 */
public class RunnableTask extends TimerTask {

	private final Runnable runnable;
	private final ErrorHandler errorHandler;

	/**
	 * Creates the task with the runnable.
	 * 
	 * @param runnable
	 *            the runnable to run.
	 */
	public RunnableTask(Runnable runnable) {
		this(runnable, null);
	}

	/**
	 * Creates the task with the runnable and a error handler.
	 * <p>
	 * The given error handler will receive all uncaught exceptions generated by the runnable.
	 * 
	 * @param runnable
	 *            the runnable to run.
	 * @param errorHandler
	 *            the error handler to send the uncaught exceptions to.
	 * @see #uncaughtException(Timer, Throwable)
	 */
	public RunnableTask(Runnable runnable, ErrorHandler errorHandler) {
		this.runnable = runnable;
		this.errorHandler = errorHandler;
	}

	@Override
	public void run() {
		runnable.run();
	}

	@Override
	public void uncaughtException(Timer timer, Throwable t) {
		if (errorHandler != null) {
			errorHandler.uncaughtException(t);
		}
	}

}
