/*
 * Java
 *
 * Copyright 2014 IS2T. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be found at http://www.is2t.com/open-source-bsd-license/.
 */
package com.is2t.demo.utilities.activity;

import com.is2t.demo.utilities.errors.ErrorHandler;

public interface ActivitySupervisor {

	/**
	 * Sets the activity listener that will receive the activity notifications.
	 * 
	 * @param activityListener
	 *            the activity listener to notify.
	 */
	void setActivityListener(ActivityListener activityListener);

	/**
	 * Starts supervising activity.
	 */
	void arm();

	/**
	 * Stops to supervise.
	 */
	void stop();

	/**
	 * Sets an error handler that will receive all uncaught exceptions generated by the activity listener.
	 * 
	 * @param errorHandler
	 *            the error handler to set.
	 */
	void setErrorHandler(ErrorHandler errorHandler);

}
